### ISSUE TITLE
"Side by side" course mode

### ISSUE THREAD

**Issue by JChoquette** [SALTISES4/CourseFlow#58]
Users would like to be able to compare courses side by side within a project (or workflows in general). This should be a minimal comparison, possibly allowing the selection of just specific columns. Some amount of editing (drag and drop) would be nice, dragging and dropping between the actual courses would be great.

The same could/should be done for the outcomes.

**Comment by cathyroy** [comment]
This is not super high priority in terms of urgency, but in terms of utility/importance I would put it right up there. Would be amazing to have this functional in the fall, will make our work on term 2 so much easier.

**Comment by JChoquette** [comment]
Thanks @cathyroy, I'll remove the wishlist/low priority tag
