### ISSUE TITLE
Course Framework Export - include Elements of Competency

### ISSUE THREAD

**Issue by mlopezdawson** [SALTISES4/CourseFlow#60]
Hello Jeremie, not sure if this is the right way to do this, but here is my first request using github...

In the Course Framework Export, for a course that has assigned a full program competency, we only see the statement of the competency listed under the Ministerial Competencies Section, not the elements of the competency.  I would like to be able to see all the elements of the competency on the framework export (not the performance criteria, only the elements). This is important as the elements are referenced later on the framework under the column called 'competencies' but we don't have a way to know what each of the elements listed there means.  Thanks!

**Comment by JChoquette** [comment]
Thanks @mlopezdawson, I'll look into this. Would the third level (performance indicators) also be included here?

**Comment by mlopezdawson** [comment]
Yes, I guess I rather see all the competency information (including performance criteria) on the framework export. It is easier to hide them or delete them from the export if we don't need them. If it is too hard to add this third level, then only the statement of the competency and the elements is sufficient.

**Comment by JChoquette** [comment]
Completed and included in `outcome-sets` branch for an upcoming update.
