### ISSUE TITLE
Creating activity workflows when only having Editing access to courses (not program)

### ISSUE THREAD

**Issue by mlopezdawson** [SALTISES4/CourseFlow#66]
When a user does not have Editing access to the program project, only to one course within a program, there does not seem to be a way to create new activity level workflows. I tried creating a new project, adding an activity, but then when trying to link to the activity from the course, the only option is to copy the activity to the program project and link it (which is not allowed because the person cannot edit the program level project). Is there another option? Something I am not doing correctly? Thanks!

**Comment by JChoquette** [comment]
This is by design, as a user without editing permissions on a project should not be able to create workflows within it. This is unlikely to change any time in the near future.
